name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: npm run coverage
        run: npm run coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  blog:
    name: Deploy blog from subdirectory
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: git
        run: git subtree split --branch blog --prefix www/blog/
